services:
  poller:
    build: .
    command: python Bot/poller/main.py
    environment:
      - VALKEY_NODES=valkey-1:6379,valkey-2:6379,valkey-3:6379,valkey-10:6379,valkey-11:6379
    networks:
      - booth_evaluation_ops_default
    restart: always

  gateway-0:
    build: .
    command: python Bot/gateway/main.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SHARD_ID=0
      - TOTAL_SHARDS=2
      - VALKEY_NODES=valkey-1:6379,valkey-2:6379,valkey-3:6379,valkey-10:6379,valkey-11:6379
    networks:
      - booth_evaluation_ops_default
    restart: always

  gateway-1:
    build: .
    command: python Bot/gateway/main.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SHARD_ID=1
      - TOTAL_SHARDS=2
      - VALKEY_NODES=valkey-1:6379,valkey-2:6379,valkey-3:6379,valkey-10:6379,valkey-11:6379
    networks:
      - booth_evaluation_ops_default
    restart: always

  worker-0:
    build: .
    command: python Bot/worker/main.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - VALKEY_NODES=valkey-1:6379,valkey-2:6379,valkey-3:6379,valkey-10:6379,valkey-11:6379
    networks:
      - booth_evaluation_ops_default
    restart: always

  worker-1:
    build: .
    command: python Bot/worker/main.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - VALKEY_NODES=valkey-1:6379,valkey-2:6379,valkey-3:6379,valkey-10:6379,valkey-11:6379
    networks:
      - booth_evaluation_ops_default
    restart: always

networks:
  booth_evaluation_ops_default:
    external: true
